### ISSUE TITLE
Add a mini header on each page of the app.

### ISSUE THREAD

**Issue by Starboy-Sharma** [Starboy-Sharma/sprint-voter-frontend#5]
I want to add a small height header that only contains the following links for my whole application
- Home Icon - Redirect Users to /teams page
- Logout Icon - Logout user and redirect to /login page

**Comment by codecShivam** [comment]
Assign this to me....

**Comment by DivyaKandhasamy** [comment]
hi, I would love to work on this one. Can you please assign this to me?

**Comment by Starboy-Sharma** [comment]
@codecShivam I am assigning this ticket to you.

Please note you also need to set up the [backend code](https://github.com/Starboy-Sharma/sprint-voter-backend) as well or if possible you can bypass your login creds to make it work. Let me know if you are facing any issues during setup of the project

**Comment by codecShivam** [comment]
> @codecShivam I am assigning this ticket to you.
> 
> Please note you also need to set up the [backend code](https://github.com/Starboy-Sharma/sprint-voter-backend) as well or if possible you can bypass your login creds to make it work. Let me know if you are facing any issues during setup of the project

Currently i can work for frontend only , you haven't metioned about backend earlier so would you like me to continue or not? :question:

**Comment by Starboy-Sharma** [comment]
@codecShivam You don't need to work on the backend. My only intention is if you want to run this project you also need the backend code
