### ISSUE TITLE
failed to resolve

### ISSUE THREAD

**Issue by codecShivam** [Starboy-Sharma/sprint-voter-frontend#6]
I came across an issue in your project  and thought I should bring it to your attention. while loading the page by the cmd npm run  dev the website shows some error.  I would be happy to help you resolve this issue if you would like. Please let me know if you are interested in working together on this.
![Screenshot from 2023-04-05 03-26-25](https://user-images.githubusercontent.com/118369445/229932718-91cb5339-8265-4d8e-91a3-47721c156e11.png)

**Comment by Starboy-Sharma** [comment]
I found the bug in the code I will create an MR and fix this bug.

**Comment by Starboy-Sharma** [comment]
Hey @codecShivam 

Thanks for mentioning the issue

Please take a fresh pull, try again, and let me know if the issue still exists.

If the bug is fixed plz drop a comment I will close the issue 👨‍💻

**Comment by codecShivam** [comment]
:+1:  done
